version: '3'

services:
  sqlite-db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: sqlite-container
    volumes:
      - ./titanic_data.db:/app/titanic_data.db

  flask-app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: flask-container
    ports:
      - "5000:5000"
    depends_on:
      - sqlite-db
    volumes:
      - ./flask_app:/app
      - ./titanic_data.db:/app/titanic_data.db

  streamlit-app:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit-container
    ports:
      - "8501:8501"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    depends_on:
      - flask-app
    volumes:
      - ./streamlit_app:/app