services:
  database: 
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: full-database
    volumes:
      - ./database/RA_projects.db:/app/RA_projects.db

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_route
    ports:
      - 5000:5000
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - ./database/RA_projects.db:/app/RA_projects.db

  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_frontend
    ports:
      - 8501:8501
    develop:
      watch:
      - action: sync
        path: ./RA_Program.py # Watch the RA_Program.py file
        target: /app/RA_Program.py 
        command: docker-compose restart streamlit_frontend
      - action: sync
        path: ./pages # Watch the 'pages' folder
        target: /app/pages 
        command: docker-compose restart streamlit_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./database/RA_projects.db:/app/RA_projects.db