name: Integrate with SonarQube and Black

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for SonarQube to analyze history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt file

    - name: Run Black
      run: |
        pip install black
        black --check .  # Check for formatting issues

    - name: Run SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Store your SonarQube token as a secret
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Store your SonarQube host URL as a secret
      run: |
        pip install sonar-scanner
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN