name: Code Quality and Linting

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'

    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black
      run: black Final_Project

  sonarcloud:
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # SonarCloud requires Java to run

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'

    - name: Install sonar-scanner
      run: |
        python -m pip install --upgrade pip
        pip install sonar-scanner

    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

