name: Python Code Formatting with Black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install Black
      run: 
        -pip install black
        -pip install "black[jupyter]""


    - name: Run Black Check
      run: black --check . --exclude '/(env|venv)/'
